/**
 * TASK-022 — AI Features
 *
 * Server actions that wrap OpenAI:
 *   - suggestPriority        — infer priority from card title + description
 *   - generateCardDescription — expand a short title into a structured description
 *   - suggestChecklists       — generate a to-do checklist for a given card
 *
 * Requires: OPENAI_API_KEY env var  (npm install openai)
 * Rate-limited: 20 calls/org/day tracked in Organization.aiCallsToday
 */

"use server";

// Prevents Turbopack from ever creating a client-side module factory for this
// file. Without this, Turbopack's HMR proxy for the Server Action stubs fails
// when it encounters the static imports of @clerk/nextjs/server and @/lib/db
// (both of which have Node.js-only code), producing:
//   "module factory is not available. It might have been deleted in an HMR update."
// 'server-only' makes the quarantine explicit: the actual module is server-only;
// client components get RPC stubs generated by the 'use server' directive, not
// a copy of this module.
import "server-only";

import { auth }  from "@clerk/nextjs/server";
import { db }    from "@/lib/db";
import type OpenAI from "openai"; // type-only — NOT included in JS output; keeps TS types without a runtime import
import { z }     from "zod";

// `openai` is imported dynamically (await import) rather than statically.
// Reason: ai-actions.ts is imported by "use client" components (e.g. checklists.tsx)
// so Turbopack must trace its static import graph when building the client-side
// Server Action proxy. The `openai` SDK contains Node.js-specific top-level code
// that breaks Turbopack's client HMR evaluation, causing:
//   "module factory is not available. It might have been deleted in an HMR update."
// A dynamic import is invisible to the static graph — it is only resolved at
// runtime on the server, where Node.js is available.
let _openai: OpenAI | null | undefined; // undefined = not yet initialised

/** Returns the singleton OpenAI client, loading the SDK on the first call. */
async function getOpenAI(): Promise<OpenAI> {
  if (_openai === undefined) {
    const rawKey  = process.env.OPENAI_API_KEY ?? "";
    const keyValid = Boolean(rawKey) && !rawKey.includes("REPLACE") && rawKey.length >= 20;
    if (!keyValid) {
      console.warn(
        "[ai-actions] ⚠  OPENAI_API_KEY is missing or is still the placeholder value.\n" +
        "            AI features are disabled. Add your real key to .env.local:  OPENAI_API_KEY=sk-..."
      );
      _openai = null;
    } else {
      const { default: OpenAIClass } = await import("openai");
      _openai = new OpenAIClass({ apiKey: rawKey });
    }
  }
  if (!_openai) {
    throw new Error("AI features are disabled: OPENAI_API_KEY is missing or invalid. Set it in .env.local.");
  }
  return _openai;
}

const AI_MODEL       = process.env.AI_MODEL ?? "gpt-4o-mini";

// AI_DAILY_LIMIT is read at call time (not module-load time) so that
// process.env overrides (e.g. in tests) are picked up without requiring
// a module reload.
function getAiDailyLimit(): number {
  const parsed = parseInt(process.env.AI_DAILY_LIMIT ?? "", 10);
  // Guard against NaN, Infinity, and negative values so a misconfigured env
  // var cannot silently disable rate limiting.
  return Number.isFinite(parsed) && parsed >= 0 ? parsed : 50;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

async function checkRateLimit(orgId: string): Promise<{ ok: boolean; error?: string }> {
  const org = await db.organization.findUnique({
    where: { id: orgId },
    select: { aiCallsToday: true, aiCallsResetAt: true },
  });
  if (!org) return { ok: false, error: "Organization not found." };

  const now = new Date();
  const resetAt = org.aiCallsResetAt ? new Date(org.aiCallsResetAt) : null;
  const needsReset = !resetAt || resetAt < new Date(now.getFullYear(), now.getMonth(), now.getDate());

  if (needsReset) {
    await db.organization.update({
      where: { id: orgId },
      data: { aiCallsToday: 0, aiCallsResetAt: now },
    });
    return { ok: true };
  }

  if (org.aiCallsToday >= getAiDailyLimit()) {
    return { ok: false, error: `Daily AI limit of ${getAiDailyLimit()} calls reached. Resets at midnight.` };
  }

  return { ok: true };
}

async function incrementUsage(orgId: string) {
  await db.organization.update({
    where: { id: orgId },
    data: { aiCallsToday: { increment: 1 } },
  });
}

// ─── Prompt injection sanitizer ───────────────────────────────────────────────
//
// Strips characters and patterns that could be used to hijack the system prompt
// or instruct the model to behave outside its intended scope.
//
// Approach: user-supplied content is placed in the `user` role message, separate
// from the `system` instructions. This is OpenAI's recommended prompt injection
// mitigation — the model treats `system` instructions as higher-authority than
// `user` content, making injection attacks significantly harder.
//
// sanitizeForPrompt() provides an additional layer:
//   • Removes ASCII / Unicode control characters that can inject hidden text.
//   • Collapses excessive whitespace (multi-line "jailbreak" padding).
//   • Hard-caps each field to its validated Zod limit so no downstream truncation
//     can produce an ambiguous boundary.
//
function sanitizeForPrompt(input: string): string {
  return input
    // Strip null bytes and other control characters (keep \t \n \r)
    .replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, "")
    // Collapse 3+ consecutive newlines → 2 (prevents blank-line padding tricks)
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

// ─── suggestPriority ──────────────────────────────────────────────────────────

const SuggestPriorityInput = z.object({
  title:       z.string().min(1).max(255),
  description: z.string().max(2000).optional(),
});

export async function suggestPriority(
  input: z.infer<typeof SuggestPriorityInput>
): Promise<{ data?: { priority: "URGENT" | "HIGH" | "MEDIUM" | "LOW"; reasoning: string }; error?: string }> {
  const { userId, orgId } = await auth();
  if (!userId || !orgId) return { error: "Unauthorized" };

  const parsed = SuggestPriorityInput.safeParse(input);
  if (!parsed.success) return { error: parsed.error.issues[0].message };

  const rate = await checkRateLimit(orgId);
  if (!rate.ok) return { error: rate.error };

  // Sanitize and isolate user-supplied content.
  // Placing instructions in `system` and user data in `user` is OpenAI's
  // recommended mitigation against prompt injection attacks.
  const safeTitle       = sanitizeForPrompt(parsed.data.title);
  const safeDescription = parsed.data.description ? sanitizeForPrompt(parsed.data.description) : undefined;

  try {
    const completion = await (await getOpenAI()).chat.completions.create({
      model: AI_MODEL,
      messages: [
        {
          role: "system",
          content:
            "You are a project management assistant. Given a task, suggest the most appropriate priority level. " +
            'Respond with ONLY valid JSON: { "priority": "URGENT"|"HIGH"|"MEDIUM"|"LOW", "reasoning": "<1-2 sentences>" }',
        },
        {
          role: "user",
          content: `Task title: ${safeTitle}${safeDescription ? `\nDescription: ${safeDescription}` : ""}`,
        },
      ],
      response_format: { type: "json_object" },
      max_tokens: 150,
      temperature: 0.3,
    });

    await incrementUsage(orgId);

    const content = completion.choices[0]?.message?.content ?? "{}";
    const result  = JSON.parse(content) as { priority: string; reasoning: string };

    const validPriorities = ["URGENT", "HIGH", "MEDIUM", "LOW"] as const;
    const priority = validPriorities.includes(result.priority as (typeof validPriorities)[number])
      ? (result.priority as "URGENT" | "HIGH" | "MEDIUM" | "LOW")
      : "MEDIUM";

    return { data: { priority, reasoning: result.reasoning ?? "" } };
  } catch (e) {
    console.error("[SUGGEST_PRIORITY]", e);
    return { error: "AI request failed. Please try again." };
  }
}

// ─── generateCardDescription ──────────────────────────────────────────────────

const GenerateDescriptionInput = z.object({
  title:   z.string().min(1).max(255),
  context: z.string().max(500).optional(),
});

export async function generateCardDescription(
  input: z.infer<typeof GenerateDescriptionInput>
): Promise<{ data?: { description: string }; error?: string }> {
  const { userId, orgId } = await auth();
  if (!userId || !orgId) return { error: "Unauthorized" };

  const parsed = GenerateDescriptionInput.safeParse(input);
  if (!parsed.success) return { error: parsed.error.issues[0].message };

  const rate = await checkRateLimit(orgId);
  if (!rate.ok) return { error: rate.error };

  // Sanitize and isolate user-supplied content.
  const safeTitle   = sanitizeForPrompt(parsed.data.title);
  const safeContext = parsed.data.context ? sanitizeForPrompt(parsed.data.context) : undefined;

  try {
    const completion = await (await getOpenAI()).chat.completions.create({
      model: AI_MODEL,
      messages: [
        {
          role: "system",
          content:
            "You are a project management assistant. Write a clear, concise task description " +
            "for the given card title. Write 2-4 sentences describing what needs to be done, " +
            "acceptance criteria, and relevant technical notes. Keep the tone professional and " +
            "action-oriented. Do NOT use markdown headers \u2014 plain prose only.",
        },
        {
          role: "user",
          content: `Card title: ${safeTitle}${safeContext ? `\nContext: ${safeContext}` : ""}`,
        },
      ],
      max_tokens: 300,
      temperature: 0.5,
    });

    await incrementUsage(orgId);

    const description = completion.choices[0]?.message?.content?.trim() ?? "";
    return { data: { description } };
  } catch (e) {
    console.error("[GENERATE_DESCRIPTION]", e);
    return { error: "AI request failed. Please try again." };
  }
}

// ─── suggestChecklists ────────────────────────────────────────────────────────

const SuggestChecklistInput = z.object({
  title:       z.string().min(1).max(255),
  description: z.string().max(2000).optional(),
});

export async function suggestChecklists(
  input: z.infer<typeof SuggestChecklistInput>
): Promise<{ data?: { items: string[] }; error?: string }> {
  const { userId, orgId } = await auth();
  if (!userId || !orgId) return { error: "Unauthorized" };

  const parsed = SuggestChecklistInput.safeParse(input);
  if (!parsed.success) return { error: parsed.error.issues[0].message };

  const rate = await checkRateLimit(orgId);
  if (!rate.ok) return { error: rate.error };

  // Sanitize and isolate user-supplied content.
  const safeTitle       = sanitizeForPrompt(parsed.data.title);
  const safeDescription = parsed.data.description ? sanitizeForPrompt(parsed.data.description) : undefined;

  try {
    const completion = await (await getOpenAI()).chat.completions.create({
      model: AI_MODEL,
      messages: [
        {
          role: "system",
          content:
            "You are a project management assistant. Generate a practical checklist for the given task. " +
            'Respond with ONLY valid JSON: { "items": ["<checklist item>", ...] } ' +
            "Provide 4-8 actionable items. Each item should be a short imperative sentence " +
            '(e.g., "Write unit tests for the auth module").',
        },
        {
          role: "user",
          content: `Task: ${safeTitle}${safeDescription ? `\nDescription: ${safeDescription}` : ""}`,
        },
      ],
      response_format: { type: "json_object" },
      max_tokens: 400,
      temperature: 0.4,
    });

    await incrementUsage(orgId);

    const content = completion.choices[0]?.message?.content ?? "{}";
    const result  = JSON.parse(content) as { items?: unknown };
    const items   = Array.isArray(result.items)
      ? (result.items as unknown[]).filter((i): i is string => typeof i === "string").slice(0, 8)
      : [];

    return { data: { items } };
  } catch (e) {
    console.error("[SUGGEST_CHECKLISTS]", e);
    return { error: "AI request failed. Please try again." };
  }
}
